# Cocktails
cocktails:
- cocktail:
    name: 'cuba libre'
    ingredients:
        - incr:
            type: 'white rum'
            amount: 5.0
        - incr:
            type: 'cola'
            amount: 12.0
- cocktail:
    name: 'tams libre'
    ingredients:
        - incr:
            type: 'white rum'
            amount: 2.5
        - incr:
            type: 'gin'
            amount: 2.5
        - incr:
            type: cola
            amount: 12.0